sudo: required
language: cpp

compiler:
  - clang
  - g++

os:
  - linux
  - osx

# whitelist
branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq [packages list]

before_script: cd tests && mv Makefile MakefileTest

script: make && ( cd tests && make -f MakefileTest &&  ./TestBin)
