sudo: required
language: cpp

compiler:
  - clang
  - g++

os:
  - linux
  - osx
  
# whitelist
branches:
  only:
    - master

before_script:
  - echo "Dir:" && ls -al;

script:
  - make && (cd tests &&  make -f MakefileTest && ./TestBin)
