sudo: required
language: cpp

compiler:
  - clang
  - g++

os:
  - linux
  - osx

# whitelist
branches:
  only:
    - master

script:
  - cd tests && mv Makefile MakefileTest
  - make && ( cd tests && make -f MakefileTest &&  ./TestBin)