sudo: required
language: cpp

compiler:
  - clang
  - g++

os:
  - linux
  - osx

# whitelist
branches:
  only:
    - master

script:
  - echo "Dir: " && ls -al
  - make
  - cd tests &&  make -f MakefileTest && ./TestBin