sudo: required
language: cpp

compiler:
  - clang
  - g++

os:
  - linux
  - osx

addons:
 apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
	    - g++-4.8

# whitelist
branches:
  only:
    - master

before_script:
  - echo "Dir:" && ls -al;

script:
  - make && (cd tests &&  make -f MakefileTest && ./TestBin)
