sudo: required

language: cpp

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

compiler:
  - clang
  - g++

os:
  - linux
  - osx

# whitelist
branches:
  only:
    - master

addons:
  apt:
   packages:
     - tree

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tree; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install tree; fi

before_script:
  - echo "Data:" && ls -al;
  - tree -CFL 3

script:
  - (make && ./Bin)  && (cd tests &&  make -f MakefileTest && ./TestBin)
  - tree -CFL 3